title: A Jekyll Blog Page
author: Modified by AgentHarry5464
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A basic site blog mock-up. This was created automatically by
  GitHub, and has been modified for training purposes by
  AgentHarry5464.
  
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
